/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Activity: typeof import('./src/components/Activity.vue')['default']
    BlurReveal: typeof import('./src/components/ui/blur-reveal/BlurReveal.vue')['default']
    Community: typeof import('./src/components/Community.vue')['default']
    copy: typeof import('./src/components/TopNav copy.vue')['default']
    Dock: typeof import('./src/components/ui/dock/Dock.vue')['default']
    DockIcon: typeof import('./src/components/ui/dock/DockIcon.vue')['default']
    DockSeparator: typeof import('./src/components/ui/dock/DockSeparator.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeArticle: typeof import('./src/components/HomeArticle.vue')['default']
    HomeImage: typeof import('./src/components/HomeImage.vue')['default']
    ImageScroll: typeof import('./src/components/ImageScroll.vue')['default']
    Marquee: typeof import('./src/components/ui/marquee/Marquee.vue')['default']
    Match: typeof import('./src/components/Match.vue')['default']
    MatchCalendar: typeof import('./src/components/MatchCalendar.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    ReviewCard: typeof import('./src/components/ui/marquee/ReviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolTeam: typeof import('./src/components/SchoolTeam.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
